widoco_base_url: "https://w3id.org/gcdfos/salmon/widoco/index.html#"

themes:
  - id: stock_assessment
    label: "Stock Assessment Methods"
    query_file: "stock-assessment-terms.rq"
    output_csv: "stock-assessment-terms.csv"
    theme_iri: "https://w3id.org/gcdfos/salmon#StockAssessmentTheme"
 
  - id: legislation
    label: "Legislation and Policy"
    query_file: "legislation-terms.rq"
    output_csv: "legislation-terms.csv"
    theme_iri: "https://w3id.org/gcdfos/salmon#PolicyGovernanceTheme"

  - id: sar_recovery
    label: "Species At Risk and Recovery"
    query_file: "sar-recovery-terms.rq"
    output_csv: "sar-recovery-terms.csv"
    theme_iri: "https://w3id.org/gcdfos/salmon#SpeciesAtRiskRecoveryTheme"

  - id: data_model_provenance
    label: "Data and Model Provenance"
    query_file: "data-model-provenance-terms.rq"
    output_csv: "data-model-provenance-terms.csv"
    theme_iri: "https://w3id.org/gcdfos/salmon#DataModelProvenanceTheme"
